name: release

on:
  push:
    tags:
      - "app-v*"

env:
  srcdir : "src"

jobs:
  build-and-release:  
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1

      - name: Ensure dotnet SDK installed
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ${{ env.srcdir }}/global.json

      - name: Build applicaiton
        shell: pwsh
        working-directory: ${{ env.srcdir }}
        run: |
          dotnet restore
          dotnet build

      - name: Publish dotnet applicaiton
        shell: pwsh
        working-directory: ${{ env.srcdir }}
        run: |
          dotnet publish -o ../publish
          Compress-Archive -Path ../publish/* ../publish.zip

      - name: Publish pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: ./publish.zip

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          files: |
            ./publish.zip
